# SonarQube configuration for Angular project
sonar.projectKey=Angular20App
sonar.projectName=Angular20App
sonar.sources=src
sonar.exclusions=**/node_modules/**,**/*.spec.ts,**/*.e2e.ts,**/*.html,**/*.scss,**/*.css,**/*.json,**/*.md,**/*.txt,**/*.gitignore,**/*.editorconfig,**/*.angular/**/*,**/public/**/*,**/.vscode/**/*,**/tsconfig*.json,**/angular.json,**/package*.json,**/README.md,**/llms.txt,**/styles.scss,**/index.html,**/main.ts,**/app.html,**/app.scss,**/app.spec.ts,**/app.routes.ts,**/app.config.ts,**/vehicle.ts,**/resource-api-service.ts,**/resource-api-with-dbouncetime-service.ts,**/app.ts,**/signal-forms/**/*,**/resource-api-with-doboucetime/**/*,**/resource-api/**/*,**/directives/**/*,**/interceptors/**/*,**/resource-rx-resource/**/*,**/signal/**/*,**/linked-signal/**/*,**/vehicle-selection/**/*

# Exclude test files from coverage (if you run coverage later)
sonar.coverage.exclusions=**/*.spec.ts,**/*.e2e.ts

# (Optional) If you run coverage (e.g. via ng test --code-coverage) and have a coverage report (e.g. in coverage/lcov.info), uncomment the following lines:
# sonar.javascript.lcov.reportPaths=coverage/lcov.info 